# Generated by Django 2.1.1 on 2020-01-07 10:28

import core.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=255)),
                ('initials', models.CharField(blank=True, max_length=10, null=True, verbose_name='initials')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_visit', models.DateTimeField(null=True)),
                ('external_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('contrib.case_actions.http_request', 'HTTP Request'), ('contrib.case_actions.mozard', 'Mozard koppelverzoek'), ('contrib.case_actions.send_email', 'Send email')], max_length=255)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to=core.models.upload_to)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': (('can_manage_cases', 'Can manage cases'),),
            },
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('metadata', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Case')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='core.CaseType')),
            ],
            options={
                'ordering': ['case_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PhaseField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('BooleanField', 'BooleanField'), ('ChoiceField', 'ChoiceField'), ('MultipleChoiceField', 'MultipleChoiceField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField')], max_length=255)),
                ('widget', models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('NumberInput', 'NumberInput'), ('EmailInput', 'EmailInput'), ('URLInput', 'URLInput'), ('Textarea', 'Textarea'), ('DateInput', 'DateInput'), ('DateTimeInput', 'DateTimeInput'), ('TimeInput', 'TimeInput'), ('CheckboxInput', 'CheckboxInput'), ('Select', 'Select'), ('SelectMultiple', 'SelectMultiple'), ('RadioSelect', 'RadioSelect'), ('CheckboxSelectMultiple', 'CheckboxSelectMultiple')], max_length=255, null=True)),
                ('initial', models.CharField(blank=True, max_length=255, null=True)),
                ('args', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict)),
                ('order', models.PositiveIntegerField()),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='core.Phase')),
            ],
            options={
                'ordering': ['phase', 'order'],
            },
        ),
        migrations.AddField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CaseType'),
        ),
        migrations.AddField(
            model_name='case',
            name='current_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Phase'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.Case'),
        ),
        migrations.AddField(
            model_name='action',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.Phase'),
        ),
    ]
