# Generated by Django 2.1.1 on 2020-01-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['case_type']},
        ),
        migrations.AlterModelOptions(
            name='phasefield',
            options={'ordering': ['key']},
        ),
        migrations.RemoveField(
            model_name='phase',
            name='order',
        ),
        migrations.RemoveField(
            model_name='phasefield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='phasefield',
            name='phase',
        ),
    ]
