# Generated by Django 2.1.1 on 2020-01-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200113_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhaseField',
            new_name='Field',
        ),
    ]
