# Generated by Django 2.1.1 on 2020-01-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200113_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='fields',
            field=models.ManyToManyField(to='core.Field'),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('ArrayField', 'ArrayField'), ('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('BooleanField', 'BooleanField'), ('ChoiceField', 'ChoiceField'), ('MultipleChoiceField', 'MultipleChoiceField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField')], max_length=255),
        ),
    ]
