# Generated by Django 2.1.1 on 2018-10-03 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_caselog_case'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasefields',
            name='field_type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
