# Generated by Django 2.1.1 on 2018-10-10 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_phasefields_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasefields',
            name='field_widget',
            field=models.CharField(blank=True, choices=[('TextInput', 'TextInput'), ('NumberInput', 'NumberInput'), ('EmailInput', 'EmailInput'), ('URLInput', 'URLInput'), ('Textarea', 'Textarea'), ('DateInput', 'DateInput'), ('DateTimeInput', 'DateTimeInput'), ('TimeInput', 'TimeInput'), ('CheckboxInput', 'CheckboxInput'), ('Select', 'Select'), ('SelectMultiple', 'SelectMultiple'), ('RadioSelect', 'RadioSelect'), ('CheckboxSelectMultiple', 'CheckboxSelectMultiple')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phasefields',
            name='multi_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phasefields',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('DateField', 'DateField'), ('TimeField', 'TimeField'), ('DateTimeField', 'DateTimeField'), ('DurationField', 'DurationField'), ('EmailField', 'EmailField'), ('URLField', 'URLField'), ('BooleanField', 'BooleanField'), ('ChoiceField', 'ChoiceField'), ('MultipleChoiceField', 'MultipleChoiceField'), ('FloatField', 'FloatField'), ('DecimalField', 'DecimalField')], max_length=255),
        ),
    ]
