# Generated by Django 2.1.1 on 2020-01-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200113_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
