# Generated by Django 2.1.1 on 2020-01-13 19:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phase_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['case_type', 'order']},
        ),
        migrations.AddField(
            model_name='casetype',
            name='phases',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='phase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_phases', to='core.CaseType'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='fields',
            field=models.ManyToManyField(blank=True, to='core.Field'),
        ),
    ]
