# Generated by Django 2.1.1 on 2018-10-10 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181010_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='core.CaseType'),
        ),
        migrations.AlterField(
            model_name='phasefields',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='core.Phase'),
        ),
    ]
