# Generated by Django 2.1.1 on 2020-01-13 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200113_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetype',
            name='phases',
        ),
        migrations.AlterField(
            model_name='phase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='core.CaseType'),
        ),
    ]
