# Generated by Django 2.1.1 on 2018-10-10 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181010_2257'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhaseFields',
            new_name='PhaseField',
        ),
    ]
