# Generated by Django 2.1.1 on 2020-01-13 19:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200113_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phase',
            name='fields',
        ),
        migrations.AddField(
            model_name='phase',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list),
        ),
    ]
