# Generated by Django 3.0.3 on 2020-02-13 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200113_2011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterIndexTogether(
            name='user',
            index_together={('first_name', 'last_name')},
        ),
    ]
