# Generated by Django 2.1.1 on 2018-10-10 21:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181010_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phasefield',
            name='multi_value',
        ),
        migrations.AddField(
            model_name='phasefield',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
