# Generated by Django 3.0.3 on 2020-02-13 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200213_1245'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='user',
            index_together=set(),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='core_user_first_n_7ed624_idx'),
        ),
    ]
