# Generated by Django 2.1.1 on 2018-10-10 21:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181010_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phasefield',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
