# Generated by Django 2.1.1 on 2018-10-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20181010_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='phasefield',
            name='initial',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
