# Generated by Django 2.1.1 on 2018-10-10 21:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_phasefield_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
