# Generated by Django 3.0.3 on 2020-03-31 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0013_auto_20200331_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='phase',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group'),
        ),
    ]
