# Generated by Django 3.0.3 on 2020-04-21 17:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

def forwards(apps, schema_editor):
    CaseLog = apps.get_model('core', 'CaseLog') # pylint: disable=invalid-name

    for log in CaseLog.objects.all():
        if log.performer:
            log.performer_json = {
                'username': log.performer.username,
                'email': log.performer.email,
                'first_name': log.performer.first_name,
                'last_name': log.performer.last_name,
                'company': log.performer.company
            }

            log.save(update_fields=['performer_json'])

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0014_phase_assign_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Actie'},
        ),
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-id'], 'verbose_name': 'Bijlage'},
        ),
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'permissions': (('can_manage_cases', 'Can manage cases'),), 'verbose_name': 'Zaak', 'verbose_name_plural': 'Zaken'},
        ),
        migrations.AlterModelOptions(
            name='casetype',
            options={'verbose_name': 'Zaaktype'},
        ),
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['case_type', 'key'], 'verbose_name': 'Veld', 'verbose_name_plural': 'Velden'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'ordering': ['case_type', 'order'], 'verbose_name': 'Fase'},
        ),
        migrations.AlterModelOptions(
            name='predefinedfilter',
            options={'verbose_name': 'Voorgedefinieerde filter'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'Gebruiker'},
        ),
        migrations.AlterField(
            model_name='action',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='instellingen'),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(choices=[('contrib.case_actions.http_request', 'HTTP Request'), ('contrib.case_actions.mozard', 'Mozard koppelverzoek'), ('contrib.case_actions.send_email', 'Send email')], max_length=255, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='action',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.Phase', verbose_name='fase'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CaseType', verbose_name='zaaktype'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='aangemaakt op'),
        ),
        migrations.AlterField(
            model_name='case',
            name='name',
            field=models.CharField(max_length=255, verbose_name='naam'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='performer_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.RunPython(forwards),
        migrations.RemoveField(
            model_name='caselog',
            name='performer'
        ),
        migrations.RenameField(
            model_name='caselog',
            old_name='performer_json',
            new_name='performer'
        ),
        migrations.AlterField(
            model_name='casetype',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='weergavenaam van zaak'),
        ),
        migrations.AlterField(
            model_name='casetype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='field',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='instellingen'),
        ),
        migrations.AlterField(
            model_name='field',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.CaseType', verbose_name='zaaktype'),
        ),
        migrations.AlterField(
            model_name='field',
            name='initial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='beginwaarde'),
        ),
        migrations.AlterField(
            model_name='field',
            name='key',
            field=models.SlugField(verbose_name='sleutel'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth.Group', verbose_name='wijs toe aan groep'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='case_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phases', to='core.CaseType', verbose_name='zaaktype'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='velden'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='order',
            field=models.IntegerField(verbose_name='volgorde'),
        ),
        migrations.AlterField(
            model_name='predefinedfilter',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='instellingen'),
        ),
        migrations.AlterField(
            model_name='predefinedfilter',
            name='name',
            field=models.CharField(max_length=255, verbose_name='naam'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='bedrijf'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is actief'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_visit',
            field=models.DateTimeField(null=True, verbose_name='laatste bezoek'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='telefoonnummer'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='gebruikersnaam'),
        ),
    ]
