# Generated by Django 3.0.6 on 2020-05-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200510_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('ArrayField', 'ArrayField'), ('ArrayTextField', 'ArrayTextField'), ('CheckboxField', 'CheckboxField'), ('DateField', 'DateField'), ('Heading', 'Heading'), ('NumberField', 'NumberField'), ('RadioField', 'RadioField'), ('SelectField', 'SelectField'), ('Template', 'Template'), ('TextareaField', 'TextareaField'), ('TextField', 'TextField')], max_length=255),
        ),
    ]
