# Generated by Django 2.1.1 on 2018-12-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='object_id',
        ),
        migrations.AddField(
            model_name='attachment',
            name='case',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='core.Case'),
            preserve_default=False,
        ),
    ]
