# Generated by Django 3.0.6 on 2020-05-22 13:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200510_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='conditions',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=list, verbose_name='voorwaarden'),
        ),
    ]
