# Generated by Django 2.1.1 on 2018-12-12 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20181207_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='core.Case'),
        ),
    ]
