# Generated by Django 2.1.1 on 2018-12-17 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181212_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-id']},
        ),
    ]
