# Generated by Django 2.1.1 on 2018-12-17 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181217_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actions', to='core.Phase')),
            ],
        ),
    ]
