# Generated by Django 3.0.6 on 2020-05-25 16:01

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200522_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_cases', to=settings.AUTH_USER_MODEL, verbose_name='Coördinator'),
        ),
        migrations.AlterField(
            model_name='case',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_cases', to=settings.AUTH_USER_MODEL, verbose_name='Behandelaar'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Case', verbose_name='zaak'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='datum/tijd'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='event',
            field=models.CharField(max_length=255, verbose_name='gebeurtenis'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='performer',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, verbose_name='uitgevoerd door'),
        ),
    ]
