# Generated by Django 2.1.1 on 2018-12-17 15:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='args',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(choices=[('contrib.case_actions.HttpRequest', 'contrib.case_actions.HttpRequest')], max_length=255),
        ),
    ]
