# Generated by Django 2.1.1 on 2018-12-17 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20181217_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(choices=[('contrib.case_actions.http_request', 'HTTP Request'), ('contrib.case_actions.send_email', 'Send email')], max_length=255),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='core.Case'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='performer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
