# Generated by Django 2.1.1 on 2019-02-18 08:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_caselog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselog',
            name='metadata',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
