# Generated by Django 2.1.1 on 2019-02-18 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_caselog_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselog',
            name='description',
        ),
    ]
