# Generated by Django 2.1.1 on 2019-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_caselog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caselog',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_case_manager',
            field=models.BooleanField(default=False),
        ),
    ]
