# Generated by Django 2.1.1 on 2019-02-22 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_user_is_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_case_manager',
        ),
    ]
