# Generated by Django 2.1.1 on 2019-02-22 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_user_is_case_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-id'], 'permissions': (('can_manage', 'Can manage the case'),)},
        ),
    ]
