# Generated by Django 2.1.1 on 2019-02-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190222_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-id'], 'permissions': (('can_manage_cases', 'Can manage cases'),)},
        ),
    ]
