# Generated by Django 2.1.1 on 2019-03-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190222_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetype',
            name='display_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
