# Generated by Django 2.1.1 on 2019-03-14 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_casetype_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.Case'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.Case'),
        ),
    ]
