# Generated by Django 2.1.1 on 2020-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20190314_1151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at'], 'permissions': (('can_manage_cases', 'Can manage cases'),)},
        ),
        migrations.AlterModelOptions(
            name='caselog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='action',
            name='key',
            field=models.CharField(choices=[('contrib.case_actions.http_request', 'HTTP Request'), ('contrib.case_actions.mozard', 'Mozard koppelverzoek'), ('contrib.case_actions.send_email', 'Send email')], max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
