# Generated by Django 2.1.1 on 2020-01-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_user_company'),
        ('core', '0036_attachment_name'),
    ]

    operations = [
    ]
